name: Treasury

on:
  schedule:
    - cron: "* */6 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - name: Treasury allocate seigniorage
        run: npm run treasury:allocation
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
